sudo: false
language: node_js
node_js:
  - 12
scala: 2.12.10
jdk:
  - openjdk14
# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
    - libgconf-2-4
    
cache: 
  directories:
    - ~/.cache
    - ~/.cache/Cypress
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/backend

env:
  - APP_PORT=2551 CASSANDRA_CLUSTER_HOSTS=localhost CYPRESS_HOST=http://localhost:3000 CYPRESS_ENVIRONMENT=CI HMDA_RUNTIME_MODE=dev 

# Run the Platform
before_install:
  - "[ -d backend/.git ] || git clone https://github.com/cfpb/hmda-platform.git backend"
  - cd backend
  # Reset the repo so we can have a conflict-less pull
  - git reset --hard
  - git clean -f
  - git pull
  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs -r rm
  # Workaround for broken sbt-launch download
  - "[ -f $HOME/.sbt/launchers/1.3.10/sbt-launch.jar ] || curl -L --create-dirs -o $HOME/.sbt/launchers/1.3.10/sbt-launch.jar https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.3.10/sbt-launch.jar"
  - sbt ++$TRAVIS_SCALA_VERSION  "project hmda-platform" "run" &
  - INSTITUTION_PORT=8282 sbt ++$TRAVIS_SCALA_VERSION  "project institutions-api" "run" & 
  - cd ..

install:
  - yarn install --offline

script:
  - yarn ci &       # Start Frontend
  - cypress install # Ensure cypress is available in Travis environment
  # Verify dev server availability, create test data, run test suite.
  - ./cypress/wait-for-server.sh && yarn ci-data && yarn cypress run $CONFIG $RECORD
  - kill $(jobs -p) || true # Cleanup