sudo: false
language: node_js
node_js:
  - 12
scala: 2.12.10
jdk:
  - openjdk14
# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
    - libgconf-2-4
    
cache: 
  directories:
    - ~/.cache
    - ~/.cache/Cypress
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/backend

env:
  - CASSANDRA_CLUSTER_HOSTS=localhost APP_PORT=2551

# Run the Platform
before_install:
  - "[ -d backend/.git ] || git clone https://github.com/cfpb/hmda-platform.git backend"
  - "cd backend"
  # Reset the repo so we can have a conflict-less pull
  - "git reset --hard"
  - "git clean -f"
  - "git pull"
  # - "sbt ++$TRAVIS_SCALA_VERSION -batch hmda-platform/docker:publishLocal"
  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  # - ./run_travis.sh &
  - (sbt ++$TRAVIS_SCALA_VERSION  "project hmda-platform" "run" &)
  - "cd .."

install:
  - yarn install --offline

script:
  - ./cypress/wait-for-server.sh
  - cypress install
  - yarn start -p 3000 &
  - $(npm bin)/cypress run --spec cypress/integration/filing/Filing.spec.js --config defaultCommandTimeout=10000 $RECORD
  - kill $(jobs -p) || true